# Churchkey

Churchkey is a Java library designed for those who aren't security experts and just need something that works.  It will guess the kind of key specified in the given file and automatically parse it into one of the following JCE key types:

  - java.security.interfaces.RSAPrivateKey
  - java.security.interfaces.RSAPublicKey
  - java.security.interfaces.DSAPrivateKey
  - java.security.interfaces.DSAPublicKey

Churchkey can parse public and private key files in several formats created by other programs
such as OpenSSL, OpenSSH and more.  See the full list at the bottom.

## Java Sample

[source,java]
----
import org.junit.Assert;
import org.junit.Test;
import org.tomitribe.churchkey.Key;
import org.tomitribe.churchkey.Keys;

import java.security.interfaces.RSAPublicKey;

public class ExampleTest {

    @Test
    public void test() throws Exception {

        final String pemFile = "" +
                "-----BEGIN PUBLIC KEY-----\n" +
                "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCyzNurU19lqnYhx5QI72sIX1lh\n" +
                "8cTehTmboC+DLG7UuaUHqs096M754HtP2IiHFcIQqwYNzHgKmjmfGdbk9JBkz/DN\n" +
                "eDVsA5nc7qTnsSgULXTxwHSF286IJdco5kasaJm4Xurlm3V+2oiTugraBsi1J0Ht\n" +
                "0OtHgJIlIaGxK7mY/QIDAQAB\n" +
                "-----END PUBLIC KEY-----\n";

        final Key key = Keys.decode(pemFile.getBytes());

        Assert.assertEquals(Key.Algorithm.RSA, key.getAlgorithm());
        Assert.assertEquals(Key.Format.PEM, key.getFormat());
        Assert.assertEquals(Key.Type.PUBLIC, key.getType());

        Assert.assertTrue(key.getKey() instanceof RSAPublicKey);
    }
}
----

# Supported Key Formats
Churchkey is a Java library that can read RSA and DSA that look like any of the following:

----
-----BEGIN RSA PRIVATE KEY-----
MIICXQIBAAKBgQCyzNurU19lqnYhx5QI72sIX1lh8cTehTmboC+DLG7UuaUHqs09
6M754HtP2IiHFcIQqwYNzHgKmjmfGdbk9JBkz/DNeDVsA5nc7qTnsSgULXTxwHSF
286IJdco5kasaJm4Xurlm3V+2oiTugraBsi1J0Ht0OtHgJIlIaGxK7mY/QIDAQAB
AoGAVWV8gV5nkMISe927eW0IHM6VfS8gzPqqYgbmymq9YIJuLLRKJIh92mB55M/R
...
-----END RSA PRIVATE KEY-----
----

----
-----BEGIN RSA PUBLIC KEY-----
MIGJAoGBALLM26tTX2WqdiHHlAjvawhfWWHxxN6FOZugL4MsbtS5pQeqzT3ozvng
e0/YiIcVwhCrBg3MeAqaOZ8Z1uT0kGTP8M14NWwDmdzupOexKBQtdPHAdIXbzogl
1yjmRqxombhe6uWbdX7aiJO6CtoGyLUnQe3Q60eAkiUhobEruZj9AgMBAAE=
-----END RSA PUBLIC KEY-----
----

----
-----BEGIN DSA PRIVATE KEY-----
MIIBugIBAAKBgQDfcPOECx1ps5f4GNl4fwpzO4X07FJemfPTVJoThX7P8MzueD5f
OKio1ppYSTvVRhcLDEW8NBKhoEtXgZ4L/g0f3jADftCpy0z0zRGoyj/4m00X97CN
0X+1E2IUqe1ua+RQfEzd/XIYPSUFEe3NACznW8gy/HfsoQeUsyxAFkOEEwIVAJy7
...
-----END DSA PRIVATE KEY-----
----

----
-----BEGIN PRIVATE KEY-----
MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBALLM26tTX2WqdiHH
lAjvawhfWWHxxN6FOZugL4MsbtS5pQeqzT3ozvnge0/YiIcVwhCrBg3MeAqaOZ8Z
1uT0kGTP8M14NWwDmdzupOexKBQtdPHAdIXbzogl1yjmRqxombhe6uWbdX7aiJO6
CtoGyLUnQe3Q60eAkiUhobEruZj9AgMBAAECgYBVZXyBXmeQwhJ73bt5bQgczpV9
...
-----END PRIVATE KEY-----
----

----
-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCyzNurU19lqnYhx5QI72sIX1lh
8cTehTmboC+DLG7UuaUHqs096M754HtP2IiHFcIQqwYNzHgKmjmfGdbk9JBkz/DN
eDVsA5nc7qTnsSgULXTxwHSF286IJdco5kasaJm4Xurlm3V+2oiTugraBsi1J0Ht
0OtHgJIlIaGxK7mY/QIDAQAB
-----END PUBLIC KEY-----
----

----
ssh-dss AAAAB3NzaC1kc3MAAACBAN9w84QLHWmzl/gY2Xh/CnM7hfTsUl6Z89NUmhOFfs/wzO54Pl84qKjWmlhJO9VGFwsMRbw0EqGgS1eBngv+DR/eMAN+0KnLTPTNEajKP/ibTRf3sI3Rf7UTYhSp7W5r5FB8TN39chg9JQUR7c0ALOdbyDL8d+yhB5SzLEAWQ4QTAAAAFQCcu9GKMJJyX8go6w1gn93Xi1/EDwAAAIBJYC9VGyg80b7DF8+fHKfezGEjjRgJOVMJQA946vA3A+cntFUU+Y1LayXJ2y... dblevins@mingus.lan
----

----
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQCyzNurU19lqnYhx5QI72sIX1lh8cTehTmboC+DLG7UuaUHqs096M754HtP2IiHFcIQqwYNzHgKmjmfGdbk9JBkz/DNeDVsA5nc7qTnsSgULXTxwHSF286IJdco5kasaJm4Xurlm3V+2oiTugraBsi1J0Ht0OtHgJIlIaGxK7mY/Q== dblevins@mingus.lan
----

----
---- BEGIN SSH2 PUBLIC KEY ----
Comment: "1024-bit RSA, converted by dblevins@mingus.lan from OpenSSH"
AAAAB3NzaC1yc2EAAAADAQABAAAAgQCyzNurU19lqnYhx5QI72sIX1lh8cTehTmboC+DLG
7UuaUHqs096M754HtP2IiHFcIQqwYNzHgKmjmfGdbk9JBkz/DNeDVsA5nc7qTnsSgULXTx
wHSF286IJdco5kasaJm4Xurlm3V+2oiTugraBsi1J0Ht0OtHgJIlIaGxK7mY/Q==
---- END SSH2 PUBLIC KEY ----
----


# Maven Coordinates

[source,xml]
----
<dependency>
  <groupId>org.tomitribe</groupId>
  <artifactId>churchkey</artifactId>
  <version>0.1-SNAPSHOT</version>
</dependency>
----

