#
# Copyright (c) 2021, 2022 - Yupiik SAS - https://www.yupiik.com
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: Github CI

on: [push, pull_request]

env:
  MAVEN_OPTS: -Dmaven.repo.local=/home/runner/work/churchkey/churchkey/.m2 -Dmaven.artifact.threads=256

jobs:
  build:
    name: Main Build
    runs-on: ubuntu-20.04
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Cache Maven Repository
        uses: actions/cache@v3
        with:
          path: /home/runner/work/churchkey/churchkey/.m2
          key: m2_repository
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - run: echo "JAVA_HOME_17=$JAVA_HOME" >> $GITHUB_ENV
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
      - run: echo "JAVA_HOME_8=$JAVA_HOME" >> $GITHUB_ENV
      - name: Set up Toolchain
        shell: bash
        run: |
          mkdir -p $HOME/.m2 \
          && cat << EOF > $HOME/.m2/toolchains.xml
          <?xml version="1.0" encoding="UTF8"?>
          <toolchains>
            <toolchain>
              <type>jdk</type>
              <provides>
                <vendor>zulu</vendor>
                <version>8</version>
              </provides>
              <configuration>
                <jdkHome>${{ env.JAVA_HOME_8 }}</jdkHome>
              </configuration>
            </toolchain>
            <toolchain>
              <type>jdk</type>
              <provides>
                <vendor>zulu</vendor>
                <version>17</version>
              </provides>
              <configuration>
                <jdkHome>${{ env.JAVA_HOME_17 }}</jdkHome>
              </configuration>
            </toolchain>
          </toolchains>
          EOF
      - name: Build
        run: mvn package surefire:test@pem-dep-free -Dm2.location=/home/runner/work/churchkey/churchkey/.m2
      - name: Remove Snapshots Before Caching
        run: find /home/runner/work/churchkey/churchkey/.m2 -name '*SNAPSHOT' | xargs rm -Rf

